services:
  - type: web
    name: shottenkirk-fullstack
    runtime: node
    repo: https://github.com/YOUR_USERNAME/YOUR_REPO # Update this
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5050
      - key: MONGO_URI
        sync: false
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: EMAIL_TO
        sync: false
      - key: CLIENT_URL
        sync: false