services:
  - type: web
    name: shottenkirk-fullstack
    runtime: node
    repo: https://github.com/silverfoxmediaco/shottenkirk-app
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: cd server && npm start
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5050
      - key: MONGO_URI
        sync: false
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: EMAIL_TO
        sync: false
      - key: CLIENT_URL
        sync: false